# Repaso Lineal

## Rango y rotaciones

In [1]:
import numpy as np

In [3]:
A = [[1,2,1],[-2,-3,1],[3,5,0]]

In [4]:
rango = np.linalg.matrix_rank(A)
rango

2

In [6]:
determinante = np.linalg.det(A)
determinante

1.3322676295501906e-15

In [12]:
a= np.pi/4
r = [[np.cos(a),- np.sin(a)], [np.sin(a), np.cos(a)]]
x= [[1],[0]]

In [12]:
np.dot(r,x)

array([[0.70710678],
       [0.70710678]])

In [13]:
np.linalg.det(r)

1.0

## Matrices Cuadradas $A^t A= AA^t$

In [3]:
B= [[1,3,2], [3,5,1], [2,1,8]]

In [4]:
C=np.dot(np.transpose(B),B)
D = np.dot(B,np.transpose(B))

In [5]:
C==D

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [10]:
A = [[2,0],[0,2]]
x= [[1],[7]]

In [11]:
np.linalg.norm(np.dot(A,x))/ np.linalg.norm(x)

2.0

In [13]:
np.dot(np.transpose(r),r)

array([[ 1.00000000e+00, -4.26642159e-17],
       [-4.26642159e-17,  1.00000000e+00]])

## Datos Iris 

In [76]:
from sklearn.datasets import load_iris 

In [16]:
data = load_iris()

In [63]:
A = data.data

### Covarianza

In [64]:
for i in range(4):
    A[:,i] = A[:,i]- np.mean(A[:,i])

In [71]:
cov= np.dot(np.transpose(A),A)

In [72]:
cov *= (1/149)

In [73]:
cov

array([[ 0.68569351, -0.042434  ,  1.27431544,  0.51627069],
       [-0.042434  ,  0.18997942, -0.32965638, -0.12163937],
       [ 1.27431544, -0.32965638,  3.11627785,  1.2956094 ],
       [ 0.51627069, -0.12163937,  1.2956094 ,  0.58100626]])

### Einge vectores y valores

In [74]:
l,e= np.linalg.eig(cov)

In [75]:
l,e

(array([4.22824171, 0.24267075, 0.0782095 , 0.02383509]),
 array([[ 0.36138659, -0.65658877, -0.58202985,  0.31548719],
        [-0.08452251, -0.73016143,  0.59791083, -0.3197231 ],
        [ 0.85667061,  0.17337266,  0.07623608, -0.47983899],
        [ 0.3582892 ,  0.07548102,  0.54583143,  0.75365743]]))

### $e^te$

In [89]:
Q=np.dot(np.transpose(e),e)
Q

array([[ 1.00000000e+00,  4.62529883e-16, -1.86576071e-16,
         7.90887194e-17],
       [ 4.62529883e-16,  1.00000000e+00, -8.72605785e-16,
         1.19542195e-15],
       [-1.86576071e-16, -8.72605785e-16,  1.00000000e+00,
        -3.87091773e-15],
       [ 7.90887194e-17,  1.19542195e-15, -3.87091773e-15,
         1.00000000e+00]])

### Det(cov) vs $\Pi \lambda _i$

In [85]:
determinate= np.linalg.det(cov)
producto= np.prod(l)

In [88]:
determinate,producto

(0.0019127296684331775, 0.0019127296684331738)

### Diagonalizacion $Cov=Q\lambda IQ^t$

In [94]:
diagonal = np.identity(4)
for i in range(4):
    diagonal[i][i]*= l[i]
diagonal

array([[4.22824171, 0.        , 0.        , 0.        ],
       [0.        , 0.24267075, 0.        , 0.        ],
       [0.        , 0.        , 0.0782095 , 0.        ],
       [0.        , 0.        , 0.        , 0.02383509]])

In [98]:
covDia= np.dot(np.dot(e,diagonal), np.transpose(e))

In [99]:
covDia

array([[ 0.68569351, -0.042434  ,  1.27431544,  0.51627069],
       [-0.042434  ,  0.18997942, -0.32965638, -0.12163937],
       [ 1.27431544, -0.32965638,  3.11627785,  1.2956094 ],
       [ 0.51627069, -0.12163937,  1.2956094 ,  0.58100626]])

In [97]:
cov

array([[ 0.68569351, -0.042434  ,  1.27431544,  0.51627069],
       [-0.042434  ,  0.18997942, -0.32965638, -0.12163937],
       [ 1.27431544, -0.32965638,  3.11627785,  1.2956094 ],
       [ 0.51627069, -0.12163937,  1.2956094 ,  0.58100626]])

#### Invirtiendo al orden

In [100]:
covDiaIn= np.dot(np.dot(np.transpose(e),diagonal), e)

In [101]:
covDiaIn

array([[ 0.61439964, -0.97605028, -0.8918537 ,  0.46291876],
       [-0.97605028,  1.95469534,  1.5119132 , -0.82435966],
       [-0.8918537 ,  1.5119132 ,  1.5266638 , -0.81584859],
       [ 0.46291876, -0.82435966, -0.81584859,  0.47719827]])

## Ejemplo triangular

In [107]:
A = [[1,2,3], [0,5,7], [0,0,3]]

In [103]:
l,e = np.linalg.eig(A)

In [104]:
l,e

(array([1., 5., 3.]),
 array([[ 1.        ,  0.4472136 , -0.48154341],
        [ 0.        ,  0.89442719, -0.84270097],
        [ 0.        ,  0.        ,  0.24077171]]))

Los eingevalores son igual a la diagonal